###############################################################
#  Generated by:      Cadence Innovus 21.19-s058_1
#  OS:                Linux x86_64(Host ID c2s3.gectcr.ac.in)
#  Generated on:      Tue May 12 11:49:31 2026
#  Design:            top_dht11_ascon_uart
#  Command:           saveDesign /home/user1/testpro/ascoo_wc/outputs/innovus/post_route.enc
###############################################################
current_design top_dht11_ascon_uart
set_clock_gating_check -rise -setup 0 
set_clock_gating_check -fall -setup 0 
create_clock [get_ports {clk}]  -name clk -period 10.000000 -waveform {0.000000 5.000000}
set_wire_load_mode top
set_input_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {btnd}]
set_input_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {dht_in}]
set_input_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {rst}]
set_input_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {btnu}]
set_output_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {led[2]}]
set_output_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {led[0]}]
set_output_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {dht_out}]
set_output_delay -add_delay 5 -clock [get_clocks {clk}] [get_ports {tx}]
set_output_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {dht_oe}]
set_output_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {led[3]}]
set_output_delay -add_delay 2 -clock [get_clocks {clk}] [get_ports {led[1]}]
set_false_path  -from [get_ports {btnu btnd}] 
